SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 500, 350
NUMBER_OF_PIPES = 4
PIPE_SIZE = PIPE_WIDTH, PIPE_HEIGHT = int(SCREEN_WIDTH / NUMBER_OF_PIPES * 1/4), SCREEN_HEIGHT
HEART_SIZE = HEART_WIDTH, HEART_HEIGHT = 20, 20
GAP_SIZE = GAP_WIDTH, GAP_HEIGHT = int(SCREEN_WIDTH / NUMBER_OF_PIPES - PIPE_WIDTH), int(SCREEN_HEIGHT * 3/7)
BIRD_SIZE = BIRD_WIDTH, BIRD_HEIGHT = 30, 20
PORTAL_SIZE = PORTAL_WIDTH, PORTAL_HEIGHT = 50, 50
PIPE_VELOCITY = HEART_VELOCITY = PORTAL_VELOCITY = -5
BIRD_ACCELERATION = 1
BIRD_VELOCITY = -5
FPS = 20
SCREEN_COLOR = (200, 200, 200)